### PR TITLE
GitOps strategy: Move deployment manifests

### PR DESCRIPTION
**Pull request by bittner**
Moves the deployment configuration manifests into the GitOps repository folder.

Adds tests for the GitOps vs the Pipeline (monorepo) deployment strategy.

### CODE REVIEW

**Comment by bittner** [comment]
Builds on Travis are failing as they use an old version of PyPy3 (PyPy 7.1.1, instead of 7.2.0). I'll try to find out how this is best solved.

It's likely that building the Docker image will also fail as we move out the Nginx configuration file and php.ini (which gets unnoticed with Spring Boot as we don't have any, currently). Will look into that, too.

**Review by ZuGao — COMMENTED** [review]
Just tested that the files are moved and it looks good. Just fix the pipeline issues and it should be good to be approved

**Comment by bittner** [comment]
Fixed PyPy3 by using Bionic, as listed on https://docs.travis-ci.com/user/languages/python/#python-versions

**Comment by bittner** [comment]
We keep non-Kubernetes deployment configuration in simply the `deployment/` folder root now (no `deployment/webserver/` folder anymore). This reduces (cognitive) complexity, and it's then straight-forward to keep a `deployment/` folder also for each microservice in a GitOps setup.

**Pull request merged**
