### PR TITLE
Add rolebindings

### PR DESCRIPTION
**Pull request by chamer81**
Add rolebinding configuration.

### CODE REVIEW

**Comment by bittner** [comment]
We now need to give the service account `admin` privileges on the demo! :bulb:

**Comment by chamer81** [comment]
Good point -- the README was updated to state this, but that's not the same as actually doing it on the demo...

**Comment by bittner** [comment]
`kubeval` [complains](https://gitlab.com/appuio/example-django/-/jobs/407140652#L102):
```
WARN - stdin contains an invalid RoleBinding - apiGroup: apiGroup is required
```
I figured that we need to run linting on the generated Kubernetes YAML files before the demo is deloyed. Yet even already locally! -- I spent some time in the weekend to write a tool for that to be integrated in the Tox configuration.

**Comment by bittner** [comment]
I gave admin privileges to the demo user on APPUiO, following the [instructions in the README](https://gitlab.com/appuio/example-django/blob/master/README.rst), and the deployment passed:
```
oc -n example-django policy add-role-to-user admin -z gitlab-ci
```
The `kustomize build | kubeval`-based validation is a bit flaky, though: When the `kustomize` command fails `kubeval` passes as it finds an "empty YAML document". Not ideal. :unamused:

**Comment by chamer81** [comment]
On Tuesday, January 21, 2020 07:13 CET, Peter Bittner <notifications@github.com> wrote: 
 
> I gave admin privileges to the demo user on APPUiO, following the [instructions in the README](https://gitlab.com/appuio/example-django/blob/master/README.rst), and the deployment passed:
> ```
> oc -n example-django policy add-role-to-user admin -z gitlab-ci
> ```
> The `kustomize build | kubeval`-based validation is a bit flaky, though: When the `kustomize` command fails `kubeval` passes as it finds an "empty YAML document". Not ideal. :unamused:  
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/painless-software/painless-continuous-delivery/pull/69#issuecomment-576534101 
 
Cool.  I saw the deployment error emails and figured that was the problem. :D 
-- 
Carole Hamer
DevOps Engineer

VSHN AG | Neugasse 10 | CH-8005 Zürich
T: +41 44 545 53 00 | https://vshn.ch

**Pull request merged**
